python ./Snake-DQN_DoubleDQNandε-greedy.py \
    --gridsize 15 \
    --num_episodes 1200 \
    --target_update_frequency 5 \
    --lr 1e-3 \
    --num_updates 20 \
    --batch_size 512 \
    --num_games 30 \
    --checkpoint_dir ./greedyTr1e-3_tgt5_iter20_2 \
    --epsilon_start 1.0 \
    --epsilon_min 0.05 \
    --decay_rate 0.99